module.exports = [
  require('./user'),
  require('./bus_schedule'),
  require('./vehicle_type'),
  require('./bus'),
  require('./city'),
  require('./location'),
  require('./office'),
  require('./role'),
  require('./route'),
  require('./ticket'),
  require('./transaction'),
  require('./contact'),
  require('./transport'),
];
